name: Update High Scores

on:
  repository_dispatch:
    types: [update-high-scores]

jobs:
  update_high_scores:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update high scores
      run: |
        echo ${{ github.event.client_payload.name }} ${{ github.event.client_payload.score }}
        jq --arg name "${{ github.event.client_payload.name }}" --argjson score "${{ github.event.client_payload.score }}" \
        '. |= [{name: $name, score: $score}] + . | sort_by(-.score) | .[:3]' high_score.json > tmp.json \
        && mv tmp.json high_score.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add high_score.json
        git commit -m "Update high scores"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

