name: Update High Scores

on:
  repository_dispatch:
    types: [update-high-scores]

jobs:
  updateHighScores:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update high scores
      run: |
        echo "Updating high scores"
        python update_high_scores.py
      env:
        PLAYER_NAME: ${{ github.event.client_payload.PLAYER_NAME }}
        PLAYER_SCORE: ${{ github.event.client_payload.PLAYER_SCORE }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Update high scores
      run: |
        echo "Updating high scores"
        python update_high_scores.py
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
